web:
environment:
  VIRTUAL_HOST: "mattstates.com,www.mattstates.com"
  LETSENCRYPT_HOST: "mattstates.com,www.mattstates.com"
  LETSENCRYPT_EMAIL: "mattstates@icloud.com"
  expose:
   - "5000"
  image: mattstates:latest
  restart: always