version: "3"

volumes:
  secrets:
    external: true

services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 8080:8080
    restart: always

  nginx:
    image: nginx
    depends_on:
      - reverseproxy

  dotnetruntime:
    depends_on:
      - dotnetsdk
    image: microsoft/dotnet:2.1-aspnetcore-runtime

  dotnetsdk:
    image: microsoft/dotnet:2.1-sdk

  mattstates:
    depends_on:
      - dotnetruntime
    image: mattstates:latest
    environment:
      - USER_SECRETS_ID=65015713-1466-415e-8bdd-aa3c1034d755
    ports:
      - 80
    volumes:
      - secrets:/root/.microsoft/usersecrets/65015713-1466-415e-8bdd-aa3c1034d755
