version: '3'

volumes:
    secrets:
        external: true

services:
    reverseproxy:
        image: mstates/reverseproxy
        ports:
            - 80:80
            - 443:443
        restart: always

    nginx:
        image: nginx
        depends_on:
            - reverseproxy

    dotnetsdk:
        image: microsoft/dotnet:2.1-sdk

    dotnetruntime:
        depends_on:
            - dotnetsdk
        image: microsoft/dotnet:2.1-aspnetcore-runtime

    mattstates:
        depends_on:
            - dotnetruntime
        image: mstates/mattstates:latest
        environment:
            - USER_SECRETS_ID=65015713-1466-415e-8bdd-aa3c1034d755
        ports:
            - 80
            - 443
        volumes:
            # "run docker volume inspect" to find the mount point to create the .json file.
            - secrets:/root/.microsoft/usersecrets/65015713-1466-415e-8bdd-aa3c1034d755
